server:
  port: 8083
  servlet.context-path: /api

spring:
  profiles.active: dev
  application.name: ExamenTecso
      
---
#DEV CONFIGURATION
spring:
  profiles: dev
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
        hibernate:
          temp:
            use_jdbc_metadata_defaults: false
          dialect: org.hibernate.dialect.PostgresPlusDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas: public
    locations: classpath:db/migration
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    baseline-version: 1
    baseline-on-migrate: false


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  jwt:
    header: Authorization
    prefix: 'Bearer '
    secret: mySecret
    expiration: 3600
    claims:
      refresh:
        name: Refresh
  token:
    email:
      verification:
        duration: 3600000
    password:
      reset:
        duration: 3600000
    refresh:
      duration: 2592000000
  velocity:
    templates:
      location: /templates/